// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2a2iVP4UATRAgodr-263rNmhhI-5nX_Q',
    appId: '1:278636005392:web:3c9a3d792a2e28dca6a295',
    messagingSenderId: '278636005392',
    projectId: 'substrack-8feb2',
    authDomain: 'substrack-8feb2.firebaseapp.com',
    storageBucket: 'substrack-8feb2.appspot.com',
    measurementId: 'G-XZHY2W2PVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaVDYfNK2uCccO2cMybPZ3RVb5Xy2MBGQ',
    appId: '1:278636005392:android:34e9c894bb6cf8a3a6a295',
    messagingSenderId: '278636005392',
    projectId: 'substrack-8feb2',
    storageBucket: 'substrack-8feb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGmKJhCsGjZ5zGJxYDcxJSVd86xdopoTk',
    appId: '1:278636005392:ios:e67a5433999f4df7a6a295',
    messagingSenderId: '278636005392',
    projectId: 'substrack-8feb2',
    storageBucket: 'substrack-8feb2.appspot.com',
    iosBundleId: 'com.example.substrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGmKJhCsGjZ5zGJxYDcxJSVd86xdopoTk',
    appId: '1:278636005392:ios:8604cc4e649025f2a6a295',
    messagingSenderId: '278636005392',
    projectId: 'substrack-8feb2',
    storageBucket: 'substrack-8feb2.appspot.com',
    iosBundleId: 'com.example.substrack.RunnerTests',
  );
}
